# Generated by Django 4.2.3 on 2023-08-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_pic',
            field=models.FileField(max_length=254, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(max_length=254, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
